<a href="https://colab.research.google.com/github/printer36/data-bootcamp12/blob/main/Essential_Python_for_DA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Essential Python for DA
- OOP: Object Oriented Programming
- Read and Write file
- Context Manager
- Handle Error
- Pandas & Numpy (on demand)
- Request API

## OOP

In [ ]:
class Dog:
  def __init__(self,name,species, age):
    self.name = name
    self.species = species
    self.age = age

  def bark(self):
    print(f"{self.name} says woof!")

  def hbd(self):
    self.age += 1

In [ ]:
dog1 = Dog("milo","Chihuahua",2)
dog2 = Dog("david","Husky",3)

In [ ]:
print(f"{dog1.name} is {dog1.species}")

milo is Chihuahua

In [ ]:
print(f"{dog2.name} is {dog2.species}")

david is Husky

In [ ]:
dog1.bark()

milo says woof!

In [ ]:
dog1.hbd()

In [ ]:
print(dog1.age)

3

In [ ]:
class ATM:
  def __init__(self, username, bank, amount):
    self.username = username
    self.bank = bank
    self.amount = amount

  def __str__(self):
    return f"{self.username} uses {self.bank} and has {self.amount} THB in an account."

  def check_balance(self):
    print(f"Your balance is {self.amount} THB")

  def deposit(self, saving):
    self.amount += saving
    print(f"Deposit {saving} THB successfully")

In [ ]:
printer = ATM("sarunpron","scb",100)

In [ ]:
printer.check_balance()

Your balance is 100 THB

In [ ]:
printer.deposit(100)

Deposit 100 THB successfully

In [ ]:
print(printer.amount)

200

In [ ]:
print(printer)

sarunpron uses scb and has 200 THB in an account.

In [ ]:
## super class

In [ ]:
class Person:
  def __init__(self,name,age):
    self.name = name
    self.age = age

## extension
class Employee(Person):
  def __init__(self,name,age,company):
    super().__init__(name,age)   ## refer to class Person
    self.company = company

  def greeting(self):
    print("Hello World!")

In [ ]:
person1 = Person("Printer", 27)

In [ ]:
person2 = Employee("Lisa", 28, "google")

In [ ]:
person2.greeting()

Hello World!

In [ ]:
## Try Except Block ดักจับบัค

In [ ]:
try:
  result = 1/0
except:
  print("ERROR!")

ERROR!

In [ ]:
## read file
import csv

In [ ]:
try:
  file = open("hotel.csv","r") ## r w a

  data = csv.reader(file)

  for row in data:
    print(row)

  file.close()

except FileNotFoundError:
  print("Error, check again.")
finally:
  print("read file successfully.")

['hotel_id', 'name', 'city', 'star_rating', 'price_per_night']
['101', 'Grand Plaza', 'New York', '5', '350']
['102', 'Ocean View', 'Miami', '4', '220']
['103', 'Mountain Retreat', 'Denver', '4', '185']
['104', 'The Urban Stay', 'Chicago', '3', '140']
['105', 'Sunset Resort', 'Los Angeles', '5', '410']
['106', 'Desert Inn', 'Phoenix', '3', '95']
['107', 'Heritage House', 'Boston', '4', '210']
['108', 'Lakeside Lodge', 'Seattle', '3', '130']
['109', 'Golden Gate Suites', 'San Francisco', '5', '380']
['110', 'Central Boutique', 'Austin', '4', '195']
read file successfully.

In [ ]:
# context manager
read_data = [] ## empty list

with open("hotel.csv", "r") as file:
  data = csv.reader(file)
  for row in data:
    read_data.append(row)

In [ ]:
# header
read_data[0]

['hotel_id', 'name', 'city', 'star_rating', 'price_per_night']

In [ ]:
# body data
read_data[1:]

[['101', 'Grand Plaza', 'New York', '5', '350'],
 ['102', 'Ocean View', 'Miami', '4', '220'],
 ['103', 'Mountain Retreat', 'Denver', '4', '185'],
 ['104', 'The Urban Stay', 'Chicago', '3', '140'],
 ['105', 'Sunset Resort', 'Los Angeles', '5', '410'],
 ['106', 'Desert Inn', 'Phoenix', '3', '95'],
 ['107', 'Heritage House', 'Boston', '4', '210'],
 ['108', 'Lakeside Lodge', 'Seattle', '3', '130'],
 ['109', 'Golden Gate Suites', 'San Francisco', '5', '380'],
 ['110', 'Central Boutique', 'Austin', '4', '195']]

In [ ]:
## for loop to calculate avg. price per night
prices = []

for row in read_data[1: ]:
   prices.append(int(row[-1]))  # เก็บ row ที่ index -1 ไปไว้ใน prices

print(f"Average price per night: {sum(prices)/len(prices)}")

Average price per night: 231.5

In [12]:
import pandas as pd

df = pd.read_csv("hotel.csv")

df.head()

   hotel_id              name         city  star_rating  price_per_night
0       101       Grand Plaza     New York            5              350
1       102        Ocean View        Miami            4              220
2       103  Mountain Retreat       Denver            4              185
3       104    The Urban Stay      Chicago            3              140
4       105     Sunset Resort  Los Angeles            5              410

In [13]:
df.price_per_night.mean()

np.float64(231.5)

In [14]:
df["price_per_night"].mean()

np.float64(231.5)

## Read & Write File

In [15]:
# write file + context manager

In [16]:
head = ["id", "name", "city"]
body = [
    [1, "CU", "Bangkok"],
    [2, "LSE", "London"],
    [3, "Reading", "Reading"]
]

with open("school.csv","w") as file:
  writer = csv.writer(file)
  writer.writerow(head)
  writer.writerows(body)

NameError: name 'csv' is not defined

In [17]:
!ls

hotel.csv  sample_data	school2.csv  school.csv

In [18]:
!cat school.csv

In [8]:
# modern python
import pandas as pd

df = pd.read_csv("school.csv")

df.head()

EmptyDataError: No columns to parse from file

In [9]:
# export csv file in pandas
df.to_csv("school2.csv")

In [ ]:
# read data from internet

In [10]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/penguins.csv"

In [11]:
import pandas as pd
df_penguin = pd.read_csv(url)

In [19]:
df_penguin.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [20]:
df_penguin.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [22]:
## select column
df_penguin[["species","island","body_mass_g"]].head(10)

  species     island  body_mass_g
0  Adelie  Torgersen       3750.0
1  Adelie  Torgersen       3800.0
2  Adelie  Torgersen       3250.0
3  Adelie  Torgersen          NaN
4  Adelie  Torgersen       3450.0
5  Adelie  Torgersen       3650.0
6  Adelie  Torgersen       3625.0
7  Adelie  Torgersen       4675.0
8  Adelie  Torgersen       3475.0
9  Adelie  Torgersen       4250.0

In [23]:
## filter rows
df_penguin.query("species == 'Adelie' and island == 'Dream'")

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
30,Adelie,Dream,39.5,16.7,178.0,3250.0,FEMALE
31,Adelie,Dream,37.2,18.1,178.0,3900.0,MALE
32,Adelie,Dream,39.5,17.8,188.0,3300.0,FEMALE
33,Adelie,Dream,40.9,18.9,184.0,3900.0,MALE
34,Adelie,Dream,36.4,17.0,195.0,3325.0,FEMALE
35,Adelie,Dream,39.2,21.1,196.0,4150.0,MALE
36,Adelie,Dream,38.8,20.0,190.0,3950.0,MALE
37,Adelie,Dream,42.2,18.5,180.0,3550.0,FEMALE
38,Adelie,Dream,37.6,19.3,181.0,3300.0,FEMALE
39,Adelie,Dream,39.8,19.1,184.0,4650.0,MALE
40,Adelie,Dream,36.5,18.0,182.0,3150.0,FEMALE
41,Adelie,Dream,40.8,18.4,195.0,3900.0,MALE
42,Adelie,Dream,36.0,18.5,186.0,3100.0,FEMALE
43,Adelie,Dream,44.1,19.7,196.0,4400.0,MALE
44,Adelie,Dream,37.0,16.9,185.0,3000.0,FEMALE
45,Adelie,Dream,39.6,18.8,190.0,4600.0,MALE
46,Adelie,Dream,41.1,19.0,182.0,3425.0,MALE
47,Adelie,Dream,37.5,18.9,179.0,2975.0,NaN
48,Adelie,Dream,36.0,17.9,190.0,3450.0,FEMALE
49,Adelie,Dream,42.3,21.2,191.0,4150.0,MALE
84,Adelie,Dream,37.3,17.8,191.0,3350.0,FEMALE
85,Adelie,Dream,41.3,20.3,194.0,3550.0,MALE
86,Adelie,Dream,36.3,19.5,190.0,3800.0,MALE
87,Adelie,Dream,36.9,18.6,189.0,3500.0,FEMALE
88,Adelie,Dream,38.3,19.2,189.0,3950.0,MALE
89,Adelie,Dream,38.9,18.8,190.0,3600.0,FEMALE
90,Adelie,Dream,35.7,18.0,202.0,3550.0,FEMALE
91,Adelie,Dream,41.1,18.1,205.0,4300.0,MALE
92,Adelie,Dream,34.0,17.1,185.0,3400.0,FEMALE
93,Adelie,Dream,39.6,18.1,186.0,4450.0,MALE
94,Adelie,Dream,36.2,17.3,187.0,3300.0,FEMALE
95,Adelie,Dream,40.8,18.9,208.0,4300.0,MALE
96,Adelie,Dream,38.1,18.6,190.0,3700.0,FEMALE
97,Adelie,Dream,40.3,18.5,196.0,4350.0,MALE
98,Adelie,Dream,33.1,16.1,178.0,2900.0,FEMALE
99,Adelie,Dream,43.2,18.5,192.0,4100.0,MALE
132,Adelie,Dream,36.8,18.5,193.0,3500.0,FEMALE
133,Adelie,Dream,37.5,18.5,199.0,4475.0,MALE
134,Adelie,Dream,38.1,17.6,187.0,3425.0,FEMALE
135,Adelie,Dream,41.1,17.5,190.0,3900.0,MALE
136,Adelie,Dream,35.6,17.5,191.0,3175.0,FEMALE
137,Adelie,Dream,40.2,20.1,200.0,3975.0,MALE
138,Adelie,Dream,37.0,16.5,185.0,3400.0,FEMALE
139,Adelie,Dream,39.7,17.9,193.0,4250.0,MALE
140,Adelie,Dream,40.2,17.1,193.0,3400.0,FEMALE
141,Adelie,Dream,40.6,17.2,187.0,3475.0,MALE
142,Adelie,Dream,32.1,15.5,188.0,3050.0,FEMALE
143,Adelie,Dream,40.7,17.0,190.0,3725.0,MALE
144,Adelie,Dream,37.3,16.8,192.0,3000.0,FEMALE
145,Adelie,Dream,39.0,18.7,185.0,3650.0,MALE
146,Adelie,Dream,39.2,18.6,190.0,4250.0,MALE
147,Adelie,Dream,36.6,18.4,184.0,3475.0,FEMALE
148,Adelie,Dream,36.0,17.8,195.0,3450.0,FEMALE
149,Adelie,Dream,37.8,18.1,193.0,3750.0,MALE
150,Adelie,Dream,36.0,17.1,187.0,3700.0,FEMALE
151,Adelie,Dream,41.5,18.5,201.0,4000.0,MALE

In [25]:
## select and filter
df_penguin[["species","island","body_mass_g"]].query("species == 'Adelie' and island == 'Dream'").head(10)

   species island  body_mass_g
30  Adelie  Dream       3250.0
31  Adelie  Dream       3900.0
32  Adelie  Dream       3300.0
33  Adelie  Dream       3900.0
34  Adelie  Dream       3325.0
35  Adelie  Dream       4150.0
36  Adelie  Dream       3950.0
37  Adelie  Dream       3550.0
38  Adelie  Dream       3300.0
39  Adelie  Dream       4650.0

In [26]:
## make it easy to read
df_penguin[["species","island","body_mass_g"]] \
.query("species == 'Adelie' and island == 'Dream'") \
.head(10)

   species island  body_mass_g
30  Adelie  Dream       3250.0
31  Adelie  Dream       3900.0
32  Adelie  Dream       3300.0
33  Adelie  Dream       3900.0
34  Adelie  Dream       3325.0
35  Adelie  Dream       4150.0
36  Adelie  Dream       3950.0
37  Adelie  Dream       3550.0
38  Adelie  Dream       3300.0
39  Adelie  Dream       4650.0

In [29]:
## filter without query()
df_penguin[df_penguin['body_mass_g'] >= 4500] [["species","island","body_mass_g"]]

    species     island  body_mass_g
7    Adelie  Torgersen       4675.0
17   Adelie  Torgersen       4500.0
39   Adelie      Dream       4650.0
45   Adelie      Dream       4600.0
81   Adelie  Torgersen       4700.0
..      ...        ...          ...
338  Gentoo     Biscoe       4925.0
340  Gentoo     Biscoe       4850.0
341  Gentoo     Biscoe       5750.0
342  Gentoo     Biscoe       5200.0
343  Gentoo     Biscoe       5400.0

[118 rows x 3 columns]

## Request API
how to get data via API the eas way

In [30]:
import requests

## api endpoint
url = "https://swapi.info/api/people/1"

In [32]:
response = requests.get(url)

In [37]:
response.json()

{'name': 'Luke Skywalker',
 'height': '172',
 'mass': '77',
 'hair_color': 'blond',
 'skin_color': 'fair',
 'eye_color': 'blue',
 'birth_year': '19BBY',
 'gender': 'male',
 'homeworld': 'https://swapi.info/api/planets/1',
 'films': ['https://swapi.info/api/films/1',
  'https://swapi.info/api/films/2',
  'https://swapi.info/api/films/3',
  'https://swapi.info/api/films/6'],
 'species': [],
 'vehicles': ['https://swapi.info/api/vehicles/14',
  'https://swapi.info/api/vehicles/30'],
 'starships': ['https://swapi.info/api/starships/12',
  'https://swapi.info/api/starships/22'],
 'created': '2014-12-09T13:50:51.644000Z',
 'edited': '2014-12-20T21:17:56.891000Z',
 'url': 'https://swapi.info/api/people/1'}

In [35]:
response.json()["mass"]

'77'

In [45]:
## for loop
import requests
import time

charecters = []

for i in range(5):
    url = f"https://swapi.info/api/people/{i+1}"
    response = requests.get(url)
    response_json = response.json()
    charecters.append(response_json["name"])
    print(f"Success: {i+1}")
    time.sleep(0.5)

print(charecters)

Success: 1
Success: 2
Success: 3
Success: 4
Success: 5
['Luke Skywalker', 'C-3PO', 'R2-D2', 'Darth Vader', 'Leia Organa']